### ISSUE TITLE
`Carousel` missing correct type props

### ISSUE THREAD

**Issue by TheMikeyRoss** [sikka-software/Hawa#59]
### Link to the code that reproduces this issue or a replay of the bug

i dont have one

### To Reproduce

Consume the `Carousel` component and click `ctrl` + `space` to open VS Code intelisense autocomplete and the carousel options wont show up

### Current vs. Expected behavior

It should show me the options of the carousel such as `loop` and the other options listed [here](https://www.embla-carousel.com/api/options/)

### Verify latest release

- [X] I verified that the issue exists in the latest Hawa UI Kit release

### Provide environment information

```bash
@sikka/hawa@0.25.2
```

### Which area(s) are affected? (Select all that apply)

Components

### Which section is the component from?

Elements

**Comment by zaaakher** [comment]
Thanks @TheMikeyRoss,

We're aware of this issue originating from `embla-carousel-react` and it has already been fixed [here](https://github.com/davidjerleke/embla-carousel/pull/651)


We'll be waiting for an official release of `embla-carousel-react` 

In the meantime we'll update the docs to reflect the possible options you can pass to the `Carousel` component

**Comment by zaaakher** [comment]
This is now fixed in `v0.26.21`

run `npm i @sikka/hawa@next` to use it
